"""empty message

Revision ID: 02bfbc92735e
Revises: 74520bfdec98
Create Date: 2026-03-26 21:31:32.298886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02bfbc92735e'
down_revision: Union[str, Sequence[str], None] = '74520bfdec98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_updated', sa.DateTime(), nullable=True))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', 'manager', name='userrole'),
               nullable=True,
               existing_server_default=sa.text("'user'::userrole"))
    # ### end Alembic commands ###
    op.execute("""
        UPDATE users
        SET password_updated = NOW()
        WHERE password_updated IS NULL
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('admin', 'user', 'manager', name='userrole'),
               nullable=False,
               existing_server_default=sa.text("'user'::userrole"))
    op.drop_column('users', 'password_updated')
    # ### end Alembic commands ###
