"""add_manager_role_and_user_role_field

Revision ID: 74520bfdec98
Revises: b0e62068a5fd
Create Date: 2025-12-05 01:21:18.897749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74520bfdec98'
down_revision: Union[str, Sequence[str], None] = 'b0e62068a5fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем enum тип для ролей пользователей
    userrole_enum = sa.Enum('admin', 'user', 'manager', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)
    
    # Добавляем колонку role с значением по умолчанию 'user'
    op.add_column('users', sa.Column('role', userrole_enum, nullable=True, server_default='user'))
    
    # Обновляем существующие записи, устанавливая роль 'user' для всех пользователей
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")
    
    # Делаем колонку NOT NULL после установки значений по умолчанию
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Удаляем enum тип
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
