"""fixed

Revision ID: 7e2a722b5a23
Revises: 9197872e1b96
Create Date: 2025-10-18 14:59:29.436941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e2a722b5a23'
down_revision: Union[str, Sequence[str], None] = '9197872e1b96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    """Upgrade schema."""
    # Создаем enum для tasks (если ещё не создан)
    taskstatus_enum = postgresql.ENUM(
        'NEW', 'IN_PROGRESS', 'WAITING_RESOURCES', 'REVIEW', 'COMPLETED', 
        name='taskstatus'
    )
    taskstatus_enum.create(op.get_bind(), checkfirst=True)

    taskpriority_enum = postgresql.ENUM(
        'LOW', 'MEDIUM', 'HIGH', name='taskpriority'
    )
    taskpriority_enum.create(op.get_bind(), checkfirst=True)

    # Создаем таблицу tasks
    op.create_table(
        'tasks',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', taskstatus_enum, nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.Column('assigned_to', sa.Integer(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('priority', taskpriority_enum, nullable=True),
        sa.Column('deadline', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_to'], ['users.id']),
        sa.ForeignKeyConstraint(['created_by'], ['users.id']),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)

    # Создаем новый enum для проектов
    projectstatus_enum = postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', name='projectstatus')
    projectstatus_enum.create(op.get_bind(), checkfirst=True)

    # Меняем тип колонки status в projects
    op.alter_column(
        'projects', 
        'status',
        existing_type=postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
        type_=projectstatus_enum,
        existing_nullable=True
    )

    # По желанию: удалить старый enum taskstatus, если он больше нигде не используется
    old_enum = postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', name='taskstatus')
    old_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('NEW', 'IN_PROGRESS', 'COMPLETED', name='projectstatus'),
               type_=postgresql.ENUM('NEW', 'IN_PROGRESS', 'COMPLETED', name='taskstatus'),
               existing_nullable=True)
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
