"""update_project_and_add_teams

Revision ID: 8dabe2491ba1
Revises: e8a1b2c3d4e5
Create Date: 2026-04-03 20:49:30.733697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dabe2491ba1'
down_revision: Union[str, Sequence[str], None] = 'e8a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'user_id')
    )
    op.add_column('projects', sa.Column('address', sa.JSON(), nullable=True))
    op.add_column('projects', sa.Column('budget', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('spent_budget', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'progress')
    op.drop_column('projects', 'spent_budget')
    op.drop_column('projects', 'budget')
    op.drop_column('projects', 'address')
    op.drop_table('project_members')
    # ### end Alembic commands ###
