"""empty message

Revision ID: b38188ad373c
Revises: 02bfbc92735e
Create Date: 2026-03-29 19:59:07.426756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b38188ad373c'
down_revision: Union[str, Sequence[str], None] = '02bfbc92735e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('secondname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(), nullable=True))
    op.execute("""
        UPDATE users
        SET firstname='Имя', secondname='Фамилия', position='Должность'
        WHERE firstname IS NULL
    """)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'firstname', nullable=False)
    op.alter_column('users', 'secondname', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'position')
    op.drop_column('users', 'secondname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
